package com.quagmiresystems.euler;

/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae: Triangle
 * Tn=n(n+1)/2 1, 3, 6, 10, 15, ... Pentagonal Pn=n(3n−1)/2 1, 5, 12, 22, 35, ... Hexagonal
 * Hn=n(2n−1) 1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Problem045TrianglularPentagonalHexagonal {

  public static void main(String[] args) {
    int t = 1;
    int tVel = 2;
    int tAcc = 1;
    int p = 1;
    int pVel = 4;
    int pAcc = 3;
    int h = 1;
    int hVel = 5;
    int hAcc = 4;

    t += tVel;
    tVel += tAcc;
    p += pVel;
    pVel += pAcc;
    h += hVel;
    hVel += hAcc;

    boolean found = false;

    while (!found) {
      System.out.println("t: " + t + "-- p: " + p + "-- h: " + h);
      if (t < p) {
        t += tVel;
        tVel += tAcc;
      } else if (p < h) {
        p += pVel;
        pVel += pAcc;
      } else if (h < t) {
        h += hVel;
        hVel += hAcc;
      } else {
        System.out.println(t);
        if (t != 40755) {
          found = true;
        } else {
          t += tVel;
          tVel += tAcc;
        }
      }
    }

  }

}
